In [40]:
#Machine Learning & Data Mining Coursework
#Notebook 2 – Data Cleaning, Modelling and Evaluation

#Student Name: Deny Shabtheswar
#Group: CS-26
#Peer Reviewer:
#Date: 2026.02.24

Code adapted from Code Reuse Session 2 – Load Cleaned Dataset

In [41]:
# Import pandas for data handling
import pandas as pd

# Load the cleaned classification CSV produced in Notebook 1
df_class = pd.read_csv('/content/drive/MyDrive/df_class_clean.csv')

# Display the first five rows to verify the dataset
df_class.head()

,age,income,home_ownership,emplyment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status
0,40.0,175000,RENT,3,EDUCATION,25000,8.00,0.19,N,11,0
1,40.0,90000,MORTGAGE,3,HOMEIMPROVEMENT,25000,12.42,0.39,N,14,0
2,40.0,131004,MORTGAGE,9,VENTURE,25000,7.90,0.23,N,13,0
3,40.0,150000,MORTGAGE,9,DEBTCONSOLIDATION,25000,11.89,0.17,N,11,0
4,40.0,132000,MORTGAGE,3,HOMEIMPROVEMENT,25000,16.82,0.22,N,17,0

Code adapted from Code Reuse Session 2 – Dataset Overview

In [42]:
# Show number of rows and columns
df_class.shape

(58642, 11)

In [43]:
# Show list of columns
df_class.columns

Index(['age', 'income', 'home_ownership', 'emplyment_length', 'loan_intent',
       'loan_amount', 'loan_interest_rate', 'loan_income_ratio',
       'payment_default_on_file', 'credit_history_length',
       'loan_approval_status'],
      dtype='object')

Code adapted from Code Reuse Session 2 – Define X and y

In [44]:
# Define target variable y
y = df_class['loan_approval_status']

# Define feature set X by dropping the target column
X = df_class.drop(columns=['loan_approval_status'])

In [45]:
# 1. Print the list of feature names used for modelling
print("List of Feature Names Used (X):")
print(X.columns.tolist())

List of Feature Names Used (X):
['age', 'income', 'home_ownership', 'emplyment_length', 'loan_intent', 'loan_amount', 'loan_interest_rate', 'loan_income_ratio', 'payment_default_on_file', 'credit_history_length']

In [46]:
# 2. Print the data shape output
print("\nData Shape Function Output:")
print("Features (X) Shape:", X.shape)
print("Target (y) Shape:", y.shape)

Data Shape Function Output:
Features (X) Shape: (58642, 10)
Target (y) Shape: (58642,)

Code adapted from Code Reuse Session 2 – Train/Test Split (stratified)

In [47]:
# Import train_test_split
from sklearn.model_selection import train_test_split

# Perform an 80/20 split with stratification and fixed random state
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

# Proving the Accept/Reject ratio is the same
print("Training Set Ratio:\n", y_train.value_counts(normalize=True))
print("\nTest Set Ratio:\n", y_test.value_counts(normalize=True))

Training Set Ratio:
 loan_approval_status
0    0.857609
1    0.142391
Name: proportion, dtype: float64

Test Set Ratio:
 loan_approval_status
0    0.857618
1    0.142382
Name: proportion, dtype: float64

Code adapted from Code Reuse Session 2 – Identify Column Types

In [48]:
# Show data types
X_train.dtypes

# Create a list of numeric columns (float / int)
numeric_cols = X_train.select_dtypes(include=['int64','float64']).columns.tolist()

# Create a list of categorical columns (object / category)
categorical_cols = X_train.select_dtypes(include=['object','category']).columns.tolist()

# Print the two lists for confirmation
numeric_cols, categorical_cols

(['age',
  'income',
  'emplyment_length',
  'loan_amount',
  'loan_interest_rate',
  'loan_income_ratio',
  'credit_history_length'],
 ['home_ownership', 'loan_intent', 'payment_default_on_file'])

Code adapted from Code Reuse Session 2 – Manual Categorical Encoding (get_dummies)

In [49]:
# Create one-hot encoding of categorical variables on training set
X_train_cat = pd.get_dummies(X_train[categorical_cols], drop_first=True)

# Create one-hot encoding of categorical variables on test set
X_test_cat = pd.get_dummies(X_test[categorical_cols], drop_first=True)

# Align test columns to training columns (add missing columns with zeros)
X_train_cat, X_test_cat = X_train_cat.align(X_test_cat, join='outer', axis=1, fill_value=0)

In [50]:
#Display X_train_cat
X_train_cat.head()

,home_ownership_OTHER,home_ownership_OWN,home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,payment_default_on_file_Y
4641,False,False,True,False,False,True,False,False,False
7397,False,False,True,True,False,False,False,False,True
58286,False,False,False,False,True,False,False,False,False
28483,False,False,False,True,False,False,False,False,False
11573,False,False,True,False,False,False,False,True,False

In [51]:
#Display X_test_cat
X_test_cat.head()

,home_ownership_OTHER,home_ownership_OWN,home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,payment_default_on_file_Y
24544,False,False,True,True,False,False,False,False,True
36488,False,False,False,True,False,False,False,False,False
39772,False,False,False,True,False,False,False,False,False
19043,False,False,True,False,False,False,False,False,False
56679,False,False,False,False,True,False,False,False,False

Code adapted from Code Reuse Session 2 – Manual Numeric Scaling (StandardScaler)

In [52]:
# Import StandardScaler
from sklearn.preprocessing import StandardScaler

# Create scaler instance
scaler = StandardScaler()

# Fit scaler on training numeric features and transform
X_train_num = pd.DataFrame(scaler.fit_transform(X_train[numeric_cols]), columns=numeric_cols, index=X_train.index)

# Transform test numeric features using the same scaler
X_test_num = pd.DataFrame(scaler.transform(X_test[numeric_cols]), columns=numeric_cols, index=X_test.index)

In [53]:
#Show X_train_num
X_train_num.describe()

,age,income,emplyment_length,loan_amount,loan_interest_rate,loan_income_ratio,credit_history_length
count,4.691300e+04,4.691300e+04,4.691300e+04,4.691300e+04,4.691300e+04,4.691300e+04,4.691300e+04
mean,-1.526713e-16,4.149995e-17,-1.008721e-16,8.315136e-17,1.484305e-16,3.301821e-17,1.666056e-17
std,1.000011e+00,1.000011e+00,1.000011e+00,1.000011e+00,1.000011e+00,1.000011e+00,1.000011e+00
min,-1.256417e+00,-1.988445e+00,-1.202827e+00,-1.602087e+00,-1.734088e+00,-1.739305e+00,-9.481551e-01
25%,-7.577965e-01,-7.165224e-01,-6.915095e-01,-7.711097e-01,-9.233416e-01,-7.560540e-01,-6.998823e-01
50%,-2.591756e-01,-1.781422e-01,-1.801921e-01,-2.171246e-01,2.252915e-02,-2.098032e-01,-4.516095e-01
75%,4.056523e-01,4.275354e-01,5.867839e-01,5.215222e-01,7.607697e-01,5.549479e-01,5.414816e-01
max,7.884966e+00,3.758762e+00,9.023520e+00,2.922124e+00,4.079557e+00,7.328458e+00,6.003483e+00

Code adapted from Code Reuse Session 2 – Combine numeric and encoded categorical features

In [54]:
# Concatenate numeric and one-hot categorical parts to form final training and test sets
X_train_proc = pd.concat([X_train_num, X_train_cat], axis=1)
X_test_proc  = pd.concat([X_test_num,  X_test_cat], axis=1)

# Ensure columns align exactly
X_train_proc, X_test_proc = X_train_proc.align(X_test_proc, join='outer', axis=1, fill_value=0)

# Display final shapes
X_train_proc.shape, X_test_proc.shape

((46913, 16), (11729, 16))

Code adapted from Code Reuse Session 2 – Save processed datasets

In [55]:
# Save processed datasets to CSV for later reproducibility
X_train_proc.to_csv('X_train_proc.csv', index=False)
X_test_proc.to_csv('X_test_proc.csv', index=False)
y_train.to_csv('y_train.csv', index=False)
y_test.to_csv('y_test.csv', index=False)

Code adapted from Code Reuse Session 2 – Train Base Classifiers

In [56]:
# Import classifiers
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [57]:
# Initialize Logistic Regression (increase max_iter if needed)
lr = LogisticRegression(max_iter=2000, random_state=42)

# Fit logistic regression
lr.fit(X_train_proc, y_train)

LogisticRegression(max_iter=2000, random_state=42)

In [58]:

# Initialize Gaussian Naive Bayes
nb = GaussianNB()

# Fit GaussianNB
nb.fit(X_train_proc, y_train)

GaussianNB()

In [59]:
# Initialize KNN with k=5 as baseline
knn = KNeighborsClassifier(n_neighbors=5)

# Fit KNN
knn.fit(X_train_proc, y_train)

KNeighborsClassifier()

Code adapted from Code Reuse Session 2 – Evaluate Classifiers (confusion matrix, classification report, AUC)

In [60]:
# Import evaluation metrics
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score, roc_curve

In [61]:
# Logistic Regression predictions and probabilities
y_pred_lr = lr.predict(X_test_proc)
y_proba_lr = lr.predict_proba(X_test_proc)[:,1]

In [62]:
# GaussianNB predictions and probabilities
y_pred_nb = nb.predict(X_test_proc)
y_proba_nb = nb.predict_proba(X_test_proc)[:,1]

In [63]:
# KNN predictions and probabilities
y_pred_knn = knn.predict(X_test_proc)
y_proba_knn = knn.predict_proba(X_test_proc)[:,1]

In [64]:
# Logistic Regression: confusion matrix
print("Logistic Regression confusion matrix")
print(confusion_matrix(y_test, y_pred_lr))
print()
# GaussianNB: confusion matrix
print("GaussianNB confusion matrix ")
print(confusion_matrix(y_test, y_pred_nb))
print()
# KNN: confusion matrix
print("KNN confusion matrix")
print(confusion_matrix(y_test, y_pred_knn))

Logistic Regression confusion matrix
[[9804  255]
 [ 958  712]]

GaussianNB confusion matrix
[[8544 1515]
 [ 449 1221]]

KNN confusion matrix
[[9833  226]
 [ 746  924]]

In [65]:
# Logistic Regression classification report
print("Logistic Regression classification report")
print(classification_report(y_test, y_pred_lr))


# GaussianNB classification report
print("GaussianNB classification report")
print(classification_report(y_test, y_pred_nb))


# KNN classification report
print("KNN classification report")
print(classification_report(y_test, y_pred_knn))

Logistic Regression classification report
              precision    recall  f1-score   support

           0       0.91      0.97      0.94     10059
           1       0.74      0.43      0.54      1670

    accuracy                           0.90     11729
   macro avg       0.82      0.70      0.74     11729
weighted avg       0.89      0.90      0.88     11729

GaussianNB classification report
              precision    recall  f1-score   support

           0       0.95      0.85      0.90     10059
           1       0.45      0.73      0.55      1670

    accuracy                           0.83     11729
   macro avg       0.70      0.79      0.73     11729
weighted avg       0.88      0.83      0.85     11729

KNN classification report
              precision    recall  f1-score   support

           0       0.93      0.98      0.95     10059
           1       0.80      0.55      0.66      1670

    accuracy                           0.92     11729
   macro avg       0.87      0.77      0.80     11729
weighted avg       0.91      0.92      0.91     11729

In [66]:
#Logistic Regression AUC-ROC Curve
print("AUC-ROC-Logistic Regression:", roc_auc_score(y_test, y_proba_lr))
print()
#GaussianNB  AUC-ROC Curve
print("AUC-ROC-GaussianNB:", roc_auc_score(y_test, y_proba_nb))
print()
#KNN AUC-ROC Curve
print("AUC-ROC-KNN:", roc_auc_score(y_test, y_proba_knn))

AUC-ROC-Logistic Regression: 0.8888383685953474

AUC-ROC-GaussianNB: 0.8723595457459671

AUC-ROC-KNN: 0.8644468593382874

Code adapted from Code Reuse Session 2 – GridSearchCV for hyperparameter tuning

In [67]:
# Import GridSearchCV and scoring utilities
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer, recall_score

# Create scorer that targets the reject class recall (change pos_label if your reject label is 0 or 1)
reject_recall_scorer = make_scorer(recall_score, pos_label=0)

In [68]:
# Define parameter grid for Logistic Regression
param_grid_lr = {'C':[0.01,0.1,1,10], 'class_weight':[None,'balanced']}

# Create GridSearchCV using X_train_proc and y_train
grid_lr = GridSearchCV(LogisticRegression(max_iter=2000, random_state=42),
                       param_grid=param_grid_lr,
                       cv=5,
                       scoring=reject_recall_scorer,
                       n_jobs=-1)

In [69]:
# Fit GridSearch
grid_lr.fit(X_train_proc, y_train)

# Print best params and best score
print("Best LR params:", grid_lr.best_params_)
print("Best LR CV score (reject recall):", grid_lr.best_score_)

Best LR params: {'C': 0.01, 'class_weight': None}
Best LR CV score (reject recall): 0.9769840318874807

In [70]:
# Define parameter grid for GaussianNB
param_grid_nb = {
    'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6]
}

# Create GridSearchCV object
grid_nb = GridSearchCV(
    GaussianNB(),
    param_grid=param_grid_nb,
    cv=5,
    scoring=reject_recall_scorer,
    n_jobs=-1
)

In [71]:
# Fit GridSearch on training data
grid_nb.fit(X_train_proc, y_train)

# Print best parameters
print("Best NB parameters:", grid_nb.best_params_)
# Print best cross-validation score
print("Best NB CV score:", grid_nb.best_score_)

Best NB parameters: {'var_smoothing': 1e-09}
Best NB CV score: 0.8474385647754689

In [72]:
# Define parameter grid for KNN
param_grid_knn = {
    'n_neighbors': [3, 5, 7, 9, 11],
    'weights': ['uniform', 'distance']
}

# Initialize GridSearchCV for KNN
grid_knn = GridSearchCV(
    estimator=KNeighborsClassifier(),
    param_grid=param_grid_knn,
    scoring=reject_recall_scorer,
    cv=5,
    n_jobs=-1
)

In [73]:
# Fit GridSearchCV on training data
grid_knn.fit(X_train_proc, y_train)

# Print best parameters and CV score
print("Best KNN parameters:", grid_knn.best_params_)
print("Best KNN CV Reject Recall:", grid_knn.best_score_)

Best KNN parameters: {'n_neighbors': 11, 'weights': 'uniform'}
Best KNN CV Reject Recall: 0.9839186545142244

Code adapted from Code Reuse Session 2 – Evaluate best estimators on test set

In [74]:
# Use best estimators from grid search if available
best_lr = grid_lr.best_estimator_

# Make predictions on the test set
y_pred_best_lr = best_lr.predict(X_test_proc)

# Get predicted probabilities for AUC (probability of positive class)
y_proba_best_lr = best_lr.predict_proba(X_test_proc)[:, 1]

In [75]:
# Print confusion matrix for LR
print("Logistic Regression - Confusion Matrix")
print(confusion_matrix(y_test, y_pred_best_lr))

# Print classification report for LR
print("\nLogistic Regression - Classification Report")
print(classification_report(y_test, y_pred_best_lr))

# Print AUC-ROC for LR
print("\nLogistic Regression - AUC-ROC:", roc_auc_score(y_test, y_proba_best_lr))

Logistic Regression - Confusion Matrix
[[9835  224]
 [ 999  671]]

Logistic Regression - Classification Report
              precision    recall  f1-score   support

           0       0.91      0.98      0.94     10059
           1       0.75      0.40      0.52      1670

    accuracy                           0.90     11729
   macro avg       0.83      0.69      0.73     11729
weighted avg       0.89      0.90      0.88     11729


Logistic Regression - AUC-ROC: 0.8861033078489605

In [76]:
# Gaussian Naive Bayes (best from GridSearch)
best_nb = grid_nb.best_estimator_

# Make predictions on the test set
y_pred_best_nb = best_nb.predict(X_test_proc)

# Get predicted probabilities for AUC
y_proba_best_nb = best_nb.predict_proba(X_test_proc)[:, 1]

In [77]:
# Print confusion matrix for NB
print("\nGaussianNB - Confusion Matrix")
print(confusion_matrix(y_test, y_pred_best_nb))

# Print classification report for NB
print("\nGaussianNB - Classification Report")
print(classification_report(y_test, y_pred_best_nb))

# Print AUC-ROC for NB
print("\nGaussianNB - AUC-ROC:", roc_auc_score(y_test, y_proba_best_nb))

GaussianNB - Confusion Matrix
[[8544 1515]
 [ 449 1221]]

GaussianNB - Classification Report
              precision    recall  f1-score   support

           0       0.95      0.85      0.90     10059
           1       0.45      0.73      0.55      1670

    accuracy                           0.83     11729
   macro avg       0.70      0.79      0.73     11729
weighted avg       0.88      0.83      0.85     11729


GaussianNB - AUC-ROC: 0.8723595457459671

In [78]:
# K-Nearest Neighbours (best from GridSearch)
best_knn = grid_knn.best_estimator_

# Make predictions on the test set
y_pred_best_knn = best_knn.predict(X_test_proc)

# Get predicted probabilities for AUC
y_proba_best_knn = best_knn.predict_proba(X_test_proc)[:, 1]

In [79]:
# Print confusion matrix for KNN
print("\nKNN - Confusion Matrix")
print(confusion_matrix(y_test, y_pred_best_knn))

# Print classification report for KNN
print("\nKNN - Classification Report")
print(classification_report(y_test, y_pred_best_knn))

# Print AUC-ROC for KNN
print("\nKNN - AUC-ROC:", roc_auc_score(y_test, y_proba_best_knn))

KNN - Confusion Matrix
[[9913  146]
 [ 747  923]]

KNN - Classification Report
              precision    recall  f1-score   support

           0       0.93      0.99      0.96     10059
           1       0.86      0.55      0.67      1670

    accuracy                           0.92     11729
   macro avg       0.90      0.77      0.82     11729
weighted avg       0.92      0.92      0.92     11729


KNN - AUC-ROC: 0.888934746075996

Code adapted from Code Reuse Session 2 – Voting Classifier Ensemble

In [80]:
# Import VotingClassifier
from sklearn.ensemble import VotingClassifier

# Example: combine best LR and KNN (replace with your two best models)
ensemble = VotingClassifier(estimators=[('lr', best_lr), ('knn', knn)],
                            voting='soft', n_jobs=-1)

# Fit the ensemble
ensemble.fit(X_train_proc, y_train)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=0.01, max_iter=2000,
                                                 random_state=42)),
                             ('knn', KNeighborsClassifier())],
                 n_jobs=-1, voting='soft')

In [81]:
# Make predictions
y_pred_ensemble = ensemble.predict(X_test_proc)

# Get probabilities
y_proba_ensemble = ensemble.predict_proba(X_test_proc)[:,1]

In [82]:
# Import metrics
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score

In [83]:
# Confusion matrix
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred_ensemble))

# Classification report
print(classification_report(y_test, y_pred_ensemble))

# AUC score
print("AUC:", roc_auc_score(y_test, y_proba_ensemble))

Confusion Matrix
[[9899  160]
 [ 832  838]]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95     10059
           1       0.84      0.50      0.63      1670

    accuracy                           0.92     11729
   macro avg       0.88      0.74      0.79     11729
weighted avg       0.91      0.92      0.91     11729

AUC: 0.9071967011399211

Code adapted from Code Reuse Session 2 – Save model artifacts

In [84]:
# Import joblib to save models
import joblib

In [85]:
# Save Logistic Regression
joblib.dump(best_lr, 'model_logistic_regression.pkl')

# Save Gaussian Naive Bayes
joblib.dump(best_nb, 'model_naive_bayes.pkl')

# Save KNN
joblib.dump(best_knn, 'model_knn.pkl')

# Save ensemble model
joblib.dump(ensemble, 'model_voting_ensemble.pkl')

['model_voting_ensemble.pkl']

In [86]:
#show the summary of df_class
df_class.describe()

,age,income,emplyment_length,loan_amount,loan_interest_rate,loan_income_ratio,credit_history_length,loan_approval_status
count,58642.000000,58642.000000,58642.000000,58642.000000,58642.000000,58642.000000,58642.000000,58642.000000
mean,27.549743,63249.522612,4.698868,9176.800365,10.677842,0.159235,5.813683,0.142389
std,6.019031,29654.701166,3.906941,5417.962609,3.034339,0.091692,4.029259,0.349452
min,20.000000,4200.000000,0.000000,500.000000,5.420000,0.000000,2.000000,0.000000
25%,23.000000,42000.000000,2.000000,5000.000000,7.880000,0.090000,3.000000,0.000000
50%,26.000000,58000.000000,4.000000,8000.000000,10.750000,0.140000,4.000000,0.000000
75%,30.000000,75600.000000,7.000000,12000.000000,12.990000,0.210000,8.000000,0.000000
max,75.000000,175000.000000,40.000000,25000.000000,23.220000,0.830000,30.000000,1.000000